name: Build and Deploy Docusaurus from Main Branch

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build Docusaurus site
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          rm -rf .git
          touch .nojekyll
          git init
          git checkout -b main
          git add -A
          git commit -m "Deploy Docusaurus site"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main:main
